### ISSUE TITLE
Result Verification 

### ISSUE THREAD

**Issue by karandeep8** [KryeKuzhinieri/predicting-driver-stress-using-deep-learning#2]
Sir, for the [e_models.py](https://github.com/KryeKuzhinieri/predicting-driver-stress-using-deep-learning/blob/main/scripts/e_models.py)

I have run this file using the following the code
if __name__ == "__main__":
    main(
        feature_selection="rf",  # Choose one: "lda", "pca", "autoencoder", "rf"
        classifier="loop",  # Choose one: "rf", "rnn", "loop"
        undersample=True,  # True or False
        shuffle=True,  # True or False
        path=DATASET_PATH,  # Provide the path to your dataset CSV file
    )
    Can you confirm that, if I am running the code in the proper way or not?
    
    After running this code
    I got the following results (Accuracy on the Testing Data)
    lda + rf -> 54.76
    lda + RNN -> 53.99
    pca + rf -> 54.0575
    pca + rnn -> 54.760
    autoencoder + rf -> 50.86
    autoencoder + rnn -> 52.65
    rf + rf -> 70.95
    rf + rnn -> 59.52
    
    Can you please confirm these results?
    
    And I still have to run the remaining combinations.
    So for the remaining combinations, please tell me their accuracy too. 
    It would be a great help.

**Comment by KryeKuzhinieri** [comment]
To get a full list of results you should check my paper which can be found in the **readme** file (**Table 6.1)**. For a full list of parameters check **tables 6.3-6.5**. I would suggest you to read the **methodology** section of the paper for full reproducibility. 

For easier access, here is the link to the paper: https://www.dropbox.com/s/dp3hm900j2x88j0/full_thesis_with_approvals.pdf?dl=0

**Comment by karandeep8** [comment]
Thank you, sir 
I will look into that.
